### ISSUE TITLE
Update README with Contribution & Build instructions

### ISSUE THREAD

**Issue by daedlock** [styled-components/webstorm-styled-components#10]
As the plugin is written in Kotlin. It may be helpful to have a section in README for contributers explaining how to build and test the plugin with gradle.

**Comment by prigara** [comment]
Added just a bit about contributing [here](https://github.com/styled-components/webstorm-styled-components/tree/update-readme) (will send a PR once #8 is merged), but surely we need to add a more detailed guide.
