### ISSUE TITLE
README error?

### ISSUE THREAD

**Issue by kedoska** [styled-components/webstorm-styled-components#14]
From the README at _Limitations_

> It is not yet available on JetBrains Plugin Repository. When installing the plugin from disk, you won't get update notifications for it.

But ... i got this https://plugins.jetbrains.com/plugin/9997-styled-components from [twitter](https://twitter.com/WebStormIDE/status/903615955032518656) 

Is the plug-in **Styled Components** the correct plug-in?

**Comment by daedlock** [comment]
@kedoska It is the correct plugin. Just updated the README
