### ISSUE TITLE
Not support TSX（TypeScript）

### ISSUE THREAD

**Issue by JimmyLv** [styled-components/webstorm-styled-components#18]
![image](https://user-images.githubusercontent.com/4997466/30023550-83dad81a-91a2-11e7-802a-498694d22a0e.png)

**Comment by undeadcat** [comment]
Hi!
That's strange because it works for me with .tsx files.
![image](https://user-images.githubusercontent.com/7509842/30024219-6de554e4-917b-11e7-82a5-1221b0668d8d.png)

Could you share the whole file, if possible?
Are there any exceptions?

**Comment by JimmyLv** [comment]
Hey, thanks @undeadcat. I reinstall the v1.0 then everything works fine, I raised this issue when I was using the beta version. :(
