### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by mxstbr** [styled-components/webstorm-styled-components#2]
Should go in the README :blush:

**Comment by daedlock** [comment]
@mxstbr I still need a few more days to release this for testing. There are some edge cases that need to be handled.

**Comment by mxstbr** [comment]
Let's get an alpha release out so that people can start playing around with it?!

**Comment by daedlock** [comment]
@mxstbr Alright, will finalize a couple of stuff and release an alpha version later today! 👍

**Comment by daedlock** [comment]
@mxstbr Added an alpha release here https://github.com/styled-components/webstorm-styled-components/archive/v1.0-alpha.zip and updated Readme

**Comment by mxstbr** [comment]
Awesome, looks perfect. Thanks!
