### ISSUE TITLE
Where is  IDE plugin manager

### ISSUE THREAD

**Issue by zero-t4** [styled-components/webstorm-styled-components#23]
I didnt get where it is? it would be great if you upload some screenshots
![image](https://user-images.githubusercontent.com/7101905/30108531-5fbac386-930b-11e7-903f-bd44652df305.png)
-is it is?

**Comment by undeadcat** [comment]
@zero-t4, Hi!
You're almost there.
In this window, click on 'Browse repositories', then search for 'Styled components'.

You're right. Someone should update the readme with additional screenshots.

**Comment by zero-t4** [comment]
thanks
