### ISSUE TITLE
Language injection not applied when using .extend.attrs({})

### ISSUE THREAD

**Issue by mstarkman** [styled-components/webstorm-styled-components#28]
Language injection not applied to the following code:

```js
const StyledIcon = styled(Icon)`
  height: 24px;
  width: 24px;
`

const FilterIcon = StyledIcon.extend.attrs({ iconName: 'filter' })`
  line-height: 0;
  margin-right: 1rem;
`
```

I have several instances of this not working in my code.  I am using version 1.0.4 of the plugin and everything else seems to be working properly.

**Comment by daedlock** [comment]
Reproduced this on latest plugin version. @undeadcat fyi
