### ISSUE TITLE
Move to styled-components organization?

### ISSUE THREAD

**Issue by mxstbr** [styled-components/webstorm-styled-components#3]
Seeing how high the demand for an officially supported WebStorm plugin is, do you want to move this one to the `styled-components` organization on GitHub so that others can contribute and we can have a single source of truth?

**Comment by daedlock** [comment]
Sure would love to. Tried transferring the repo to `styled-components` org but I got:

> You don't have permission to create reposotiries in styled-components organization

**Comment by mxstbr** [comment]
If you invite me to this repo I can move it and invite you to the `styled-components` org!

**Comment by mxstbr** [comment]
Ah crap, I still can't move it. I've invited you to the org, can you move it there now?

**Comment by daedlock** [comment]
Done

**Comment by mxstbr** [comment]
Awesome, very exciting times!
