### ISSUE TITLE
Conflict with English SpellChecker plugin

### ISSUE THREAD

**Issue by gartz** [styled-components/webstorm-styled-components#32]
Hi, I can't use this plugin with English SpeelChecker plugin enabled in the PHPStorm.

**Comment by prigara** [comment]
Can you please share a link to the plugin and the error messages you get (ideally log files from the IDE's menu Help - Show logs).

**Comment by undeadcat** [comment]
Not reproducible without additional information.
If this is still relevant, please provide link to plugin.

Checked that built-in IDEA spellchecker highlights typos in injected fragments.
