### ISSUE TITLE
Dark green background to template literal

### ISSUE THREAD

**Issue by davidgilbertson** [styled-components/webstorm-styled-components#37]
After installing this plugin, I see the pretty styles for CSS which is great. But the whole block is a terrible green colour.

![image](https://user-images.githubusercontent.com/4443482/33007069-1895420a-ce21-11e7-8808-80813450205c.png)

Eventually I found the setting to turn this off. Maybe worth adding this to the readme?

![image](https://user-images.githubusercontent.com/4443482/33007136-705c579e-ce21-11e7-84ce-9754071df506.png)

**Comment by daedlock** [comment]
This is not something related to the plugin but is related to the IDE. IMO,
adding this to the readme doesn’t make sense.

**Comment by davidgilbertson** [comment]
Sure, your call. But this is the out-of-the-box setting from WebStorm. So if all users experience the ugly green, maybe that's a nice little bonus tip that would be appreciated.

**Comment by ron23** [comment]
I agree with OP. I had to come here to figure that out. Would be nice to have it documented. 
As a matter of fact, I tried doing exactly that before finding this issue, but seems like the "apply" functionality doesn't actually have an immediate impact so I didn't think it works (you must save).

**Comment by tunadao1** [comment]
I agree with OP.
