### ISSUE TITLE
[Question] Can I highlight with typescript props?

### ISSUE THREAD

**Issue by FourwingsY** [styled-components/webstorm-styled-components#39]
Hi, I am using styled components with typescript.
with typescript, I need to set props into styled-components

like this

```typescript
import { HTMLProps } from 'react'
import { StyledFunction } from 'styled-components'

export function withProps<T, U extends HTMLElement = HTMLElement>(
	styledFunction: StyledFunction<HTMLProps<U>>,
): StyledFunction<T & HTMLProps<U>> {
	return styledFunction
}
```

and use like

```typescript
export const Switch = withProps<SwitchProps, HTMLDivElement>(styled.div)`
  position: relative;
  color: ${props => props.on ? 'white' : 'red'};
`
```

in this case, style in `withProps` function does not highlighted as normal `styled.div` function.

Can this plugin support this? or there is other way to solve this?

**Comment by undeadcat** [comment]
This is currently not supported. 
I think we may be able to improve this plugin to use type information to determine when to inject styles into strings (if the tag of the template literal has type StyledFunction - then there should be an injection).

As as workaround you could use the standard [ways of configuring language injections](https://www.jetbrains.com/help/idea/using-language-injections.html#injection_comments) of IDEA/WebStorm/your IDE and mark the string with a comment:

```
//language=LESS prefix=div{ suffix=}
export const Switch1 = (withProps<SwitchProps, HTMLDivElement>(styled.div))`
  position: relative;
  color: ${props => props.on ? 'white' : 'red'};
`
```
If you're using 2017.3 this would currently be equivalent.

**Comment by thomastvedt** [comment]
I tried the workaround, and the comment enabled intellisense (for LESS I guess?), but I got some errors:

`  border-top: 1px solid ${Colors.GREYBORDER};`

Error between solid and $; Mismatched property value (<border-width> || <border-style> ...

is language supposed to be LESS? I tried CSS, style.

**Comment by ryall** [comment]
How could this be added into the Language Injection settings? Would it be possible to provide an example config?

![alt](https://i.imgur.com/b2SJdC6.png)

**Comment by undeadcat** [comment]
Here's an updated workaround:
In `Preferences -> Language Injections` import [this xml file](https://gist.github.com/undeadcat/fdd710cde062bd510c6fbe33e6157bc2) using the Import button. This should create an injection like this, where 'withProps' can be replaced with a different function name:

![image](https://user-images.githubusercontent.com/7509842/38096850-93363422-337c-11e8-9656-8694c72938cd.png)

**Comment by undeadcat** [comment]
As for a more general solution, it seems like the way to go should be to inject whenever the tag expression of a template literal is inferred to be [`ThemedStyledFunction`](https://github.com/styled-components/styled-components/blob/master/typings/styled-components.d.ts#L41])
This would automatically inject styled-components code almost wherever it is accepted at runtime. This could also probably fix #40

To do that one would need to:
1) Take the [StyledComponentsInjector class](https://github.com/styled-components/webstorm-styled-components/blob/master/src/main/kotlin/com/intellij/StyledComponents/StyledComponentsInjector.kt)
2) In addition to the existing patterns, check if the expression returned `ES6TaggedTemplateExpression#getTag` has type `ThemedStyledFunction` using `JSResolveUtil#getExpressionJSType`
3) The hard part  - check  that this doesn't lead to degraded performance. :-)

I will try to get around to it, but can't promise, unfortunately. If someone else is willing to try, I can answer questions.

**Comment by ryall** [comment]
@undeadcat Thanks a bunch. I'll give this a go today. :)

I'd love to help with the permanent solution but unfortunately I don't know much about the inner workings of WebStorm - but the solution sounds perfectly reasonable and I hope to see it someday.

**Comment by undeadcat** [comment]
With 1.0.8 it's possible to add `withProps` to the [list of tags](https://github.com/styled-components/webstorm-styled-components/#configuration) to treat as styled components.

With regards to configuring injections based on type: #54 requests specifically that, keeping that issue open.
