### ISSUE TITLE
Custom methods like media.desktop`` aren't recognize 

### ISSUE THREAD

**Issue by Tzelon** [styled-components/webstorm-styled-components#40]
Hey,
I'm trying to use styled-components media query tips and tricks from here https://github.com/styled-components/styled-components/blob/master/docs/tips-and-tricks.md

Something like this:
`const Container = styled.div`
  color: #333;
  ${media.desktop`padding: 0 20px;`}
  ${media.tablet`padding: 0 10px;`}
  ${media.phone`padding: 0 5px;`}
``
But I webstorm isn't recognize the css inside the backticks. I'm assuming this is because the custom method names like desktop.. 
![image](https://user-images.githubusercontent.com/4432120/34441270-3cb7d826-ecc3-11e7-8b86-67893c46f381.png)

Is there anything I can do to fix this?

**Comment by fpoumian** [comment]
I was also trying to implement this pattern for Media Queries and I stumbled upon this issue. I would love for this plugin to support this type of "nested media queries".

**Comment by aaccurso** [comment]
This would be a really nice feature. Currently, in order to enable syntax highlight I have to implement helpers that receive a `css` object rather than a template literal.

**Comment by SilencerWeb** [comment]
yeah, it would be a cool and useful feature, I'd like to see it in the next release

**Comment by jlee1201** [comment]
possibly related to #59 ?

**Comment by jChris85** [comment]
Any updates on this? Also looking for a solution. Would be a nice feature.

**Comment by microcipcip** [comment]
@aaccurso can you provide an example of your helper? I am annoyed by this issue :(

**Comment by aaccurso** [comment]
What I meant is that you can do things like:

```javascript
import styled, { css } from 'styled-components';

const Container = styled.div`
  color: red;
  media.desktop(css`color: blue;`);
  ${props => props.hasPadding ? css`padding: 20px;` : null }
`
```

The `css` keyword gives the hint to the editor to highlight the template literal.

Not sure if this is still working though, haven't used webstorm in a while.

**Comment by microcipcip** [comment]
Thanks a lot, I have tried right now, that works, but what if I have a function that needs arguments like this? :(
```
const Container= styled.div`
  line-height: 1;
  ${bp.up('m')`
    display: none;
  `}
`
```

**Comment by aaccurso** [comment]
You should be able to invoke the function returned by `bp.up`: `${bp.up('m')(css`/.../`)}`

**Comment by microcipcip** [comment]
You are amazing....it works perfectly! I have also found another tip....if you paste the snippet in a string literal, Phpstorm will try to escape it, so for example this:
```
  ${bp.up('m')`
    display: none;
  `}
```
Will become this:
```
    ${bp.up('m')\`
    justify-content: center;
  \`}
```

To fix this behaviour, you have to use the `Menu -> Edit -> Paste Simple` command, or usually `Ctrl+Alt+Shift+V`.

**Comment by Ehesp** [comment]
My use case is:

```
// Theme export
export const desktop = (...args) => css`
  @media (min-width: 1024px) {
    ${css(...args)};
  }
`;
```

```
// Some component
const Example = styled.div`
  display: none;
  ${props => props.theme.desktop`
    display: block;
  `}
`;
```

Not sure how this is do-able with `css`?

**Comment by microcipcip** [comment]
This dosen't work?
```
// Some component
const Example = styled.div`
  display: none;
  ${props => props.theme.desktop(css`
    display: block;
  `)}
`;
```

**Comment by Ehesp** [comment]
Oh wait that does! I see how that is working now, wasn't clicking before 👍

**Comment by microcipcip** [comment]
The `css` trick had some bugs for me so I've released a package for enabling highlighting in Webstorm and PhpStorm: https://github.com/microcipcip/styled-components-media-query

**Comment by undeadcat** [comment]
Added support for configuring custom methods in 1.0.7.
See [README -> Configuration](https://github.com/styled-components/webstorm-styled-components#configuration) for details and please try it out.
