### ISSUE TITLE
Webstorm css is weirdly highlighted green

### ISSUE THREAD

**Issue by alexmzssd** [styled-components/webstorm-styled-components#41]
Using webstorm-styled-components  v1.0.5   in Webstorm 2017.3

The css syntax is highlighted just fine, but but the entire chunk of code is wrapped in a strange green highlight. 

Please find the screenshot with the issue demonstrated  attached below.

<img width="459" alt="screen shot 2018-01-09 at 11 14 33 am" src="https://user-images.githubusercontent.com/32835522/34715829-3b0f144e-f52e-11e7-8c57-ec05e118c17a.png">

**Comment by prigara** [comment]
You can change the color for the injected language in Preferences | Editor | Color Scheme | General - Code - Injected language fragment.

**Comment by iamyojimbo** [comment]
Maybe add this to the README because I had to come in here to figure out what was going on
