### ISSUE TITLE
 styled` CSS` format

### ISSUE THREAD

**Issue by SvenZhao** [styled-components/webstorm-styled-components#44]
Excuse me,  Can you let webstrom support styled` CSS` format?

**Comment by undeadcat** [comment]
If your question is "Why is the code inside ``` css`div .myDiv {color :red}` ``` not formatted?", the answer is:

It's not something that at the moment be fixed by this plugin. It's planned to be fixed in the IDE in 2018.2. These are the applicable issues: [WEB-32480](https://youtrack.jetbrains.com/issue/WEB-32480) and [WEB-28540](https://youtrack.jetbrains.com/issue/WEB-28540).

**Comment by ulrichb** [comment]
@undeadcat Is WEB-28540 also the reason, why TAB indents 2 spaces, although WebStorm is configured to 4 for the CSS language?

**Comment by undeadcat** [comment]
@ulrichb, Doesn't seem to be related to any of these issues.
I'm guessing you have 2 spaces configured in JS indent settings and 4 spaces in CSS? And wish to use 4 spaces within styled-components strings?

It works as expected for me using the latest WebStorm EAP.
Could you provide some more information - the IDE version you're using, a code sample than can be used to reproduce the issue?

**Comment by undeadcat** [comment]
@ulrichb, Try changing the indent settings for LESS language.
LESS language is used in this plugin in styled-components strings because of LESS-like features like '&' selector.

And LESS, SASS, etc. languages have the IDE defaults set to 2 spaces (unlike CSS) for what seems like historical reasons.

**Comment by ulrichb** [comment]
@undeadcat Yes! It was the Less-"INDENT_SIZE" (I'v set it now to 4).

Thanks!

**Comment by volos-st** [comment]
Thanks, changing INDENT_SIZE for LESS is help me
