### ISSUE TITLE
Support styled-components-breakpoint

### ISSUE THREAD

**Issue by daviddelusenet** [styled-components/webstorm-styled-components#47]
First of all, I ❤️ this plugin!

However, I just installed [styled-components-breakpoint](https://github.com/jameslnewell/styled-components-breakpoint) inside of my project and noticed the following:

![screen shot 2018-05-14 at 13 58 21](https://user-images.githubusercontent.com/1398418/39996148-e39c7388-577e-11e8-8025-1a37b7de2c74.png)

Can support of this package be added? 

Thanks a lot!

**Comment by microcipcip** [comment]
@daviddelusenet a little late but I've published an alternative package for media queries that works with webstorm and phpstorm highlight: https://github.com/microcipcip/styled-components-media-query

**Comment by undeadcat** [comment]
Added ability to configure additional tags in 1.0.7.
Should be possible to highlight the example above by adding `breakpoint`[ to the list of custom tag prefixes](https://github.com/undeadcat/webstorm-styled-components/#configuration).
