### ISSUE TITLE
Linting Breaks with TypeScript Interface.

### ISSUE THREAD

**Issue by izakfilmalter** [styled-components/webstorm-styled-components#53]
I am using typescript on a project and noticed that when you us an interface to type check the props on a styled-component, the linting breaks.

![image](https://user-images.githubusercontent.com/5874330/43718026-5eaec2dc-9957-11e8-8018-20eef08a0d4b.png)

**Comment by undeadcat** [comment]
@izakfilmalter, What IDE version are you using?
Generic arguments for tagged template strings (like styled.div<TabProps>)  are a TypeScript feature that was added fairly recently and are only supported since 2018.2 IDE versions.

**Comment by izakfilmalter** [comment]
I am on `2018.1.5`

**Comment by undeadcat** [comment]
@izakfilmalter, Please try 2018.2, your sample works fine for me in the new version.

Unfortunately, support for these kinds of language features has to happen on the IDE side.
There's some more details in [this comment](https://github.com/styled-components/webstorm-styled-components/pull/50#issuecomment-403246232) if you're interested.

**Comment by izakfilmalter** [comment]
@undeadcat Updating got it working thanks! Closing.
