### ISSUE TITLE
Proposal: add config to allow set custom tags

### ISSUE THREAD

**Issue by acrazing** [styled-components/webstorm-styled-components#56]
It's useful for write a high level function to use styled components. Just like the [styled decorator](https://github.com/styled-components/styled-components/issues/537#issuecomment-305466183).

This feature is slightly similar to the [Microsoft/typescript-styled-plugin#tags](https://github.com/Microsoft/typescript-styled-plugin#tags).

**Comment by brabeji** [comment]
That would be really awesome. Besides that, I think that the `injectGlobal` should be additionally recognized as stylesheet at least.

**Comment by undeadcat** [comment]
Implemented in 1.0.7.
See [README -> Configuration](https://github.com/undeadcat/webstorm-styled-components/#configuration) for details.
