### ISSUE TITLE
Enable styling it on regular template strings

### ISSUE THREAD

**Issue by vitalybe** [styled-components/webstorm-styled-components#59]
Styled-Component best practices suggest to create, instead of mix-ins, functions/constants of the shared properties, e.g:

```
const commonStyle = `
  color: ${Colors.NAVY};
  font-family: ${Fonts.FONT_FAMILY};
  font-size: ${Fonts.FONT_SIZE};
  font-weight: ${Fonts.FONT_WEIGHT};
  letter-spacing: 0.01em;
`;
```

However, I get no syntax-coloring in this case. It'd be nice if I had an option to force styling for these strings as well. For example with a custom comment, e.g:

```
// styled-component string formatting
const commonStyle = `
  color: ${Colors.NAVY};
`;
```

**Comment by undeadcat** [comment]
It's been possible for a while now to make a string instance be treated as styled-components using the IDE's built-in [language injection feature](https://www.jetbrains.com/help/webstorm/using-language-injections.html):
```
//language=LESS prefix=div{ suffix=}
const commonStyle = `
  color: ${Colors.NAVY};
`;
```
If that looks too verbose (yes, it probably is :smile: ) you could probably wrap the string in `` css` ` `` (https://www.styled-components.com/docs/api#css)? There are a few issues that seem to indicate that it might be recommended to wrap mixins in css: https://github.com/styled-components/styled-components/issues/1178, https://github.com/styled-components/styled-components-website/issues/209.

**Comment by undeadcat** [comment]
If the consumer of `commonStyle` expects *a string and nothing else*, you could also use the [configuration feature](https://github.com/styled-components/webstorm-styled-components#configuration)  in 1.0.8 to add a tag like `sc` to the list of styled components tags and alias the [`String.raw` function](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/raw) to `sc`, giving something like:
```
var Colors = {NAVY:"navy"};
console.log(`color: ${Colors.NAVY};`)

var sc = String.raw;
//highlighted as styled components
console.log(sc`color: ${Colors.NAVY};`)
```
(But the css way would probably be more idiomatic).
