### ISSUE TITLE
Code within styled-components strings not reformatted

### ISSUE THREAD

**Issue by nadavelyashiv** [styled-components/webstorm-styled-components#60]
Currently CTRL-ALT-L ("Code reformat" function of WebStorm) doesn't align styled-components' CSS as it would a CSS file.

**Comment by sambokai** [comment]
any news on this?

**Comment by crimsonsunset** [comment]
bump. any news?

**Comment by undeadcat** [comment]
Code is not reformatted because the IDE does not currently support formatting code fragments inside string with arguments.
The IDE issue is [WEB-28540](https://youtrack.jetbrains.com/issue/WEB-28540). It's currently assigned to me and is planned for 2019.2.

I'll leave this open to make it easier to search for.

**Comment by jasonsoden** [comment]
Looking forward to a fix. It's very unpleasant to use styled-components in WebStorm at the moment.

![image](https://user-images.githubusercontent.com/8482503/61817443-68ece000-ae03-11e9-9fa4-a45fa00ad0b4.png)

**Comment by iDuuck** [comment]
2019.2 isn't fixing this.

**Comment by prigara** [comment]
@iDuuck sorry, the related issue on the IDE-side was not fixed in version 2019.2. Please stay tuned!

**Comment by muratdogan17** [comment]
any news about that?

**Comment by usos0k** [comment]
any news..?

**Comment by prigara** [comment]
The WebStorm team plans to work on [WEB-34245](https://youtrack.jetbrains.com/issue/WEB-34245) in the coming month. Please stay tuned!

**Comment by itshallrun** [comment]
bump

**Comment by prigara** [comment]
Hello, the feature was implemented in the IDE version 2020.3 which you can download [here](https://www.jetbrains.com/webstorm/download/). Please give it a try! In case of any issues, please feel free to file a new issue here or on [youtrack.jetbrains.com](https://youtrack.jetbrains.com/issues/web)

**Comment by s4nt14go** [comment]
I've installed version WebStorm 2020.3.2 (Build #WS-203.7148.54, built on January 25, 2021) but doesn't fix it, the workaround I found in another thread:
Place the cared inside of the HTML code, press Alt+Enter and select "Edit HTML fragment"

**Comment by prigara** [comment]
@s4nt14go could you please provide a code sample?

**Comment by ota-fayz** [comment]
I have this behavior after ` + enter

const Item = styled.li`
[cursor]`

but I want

const Item = styled.li`
    [cursor]
`

How can I do that?
