### ISSUE TITLE
Prettier doesn't work with createGlobalStyle

### ISSUE THREAD

**Issue by LouisCuvelier** [styled-components/webstorm-styled-components#61]
Hi,

Prettier doesn't want to reformat code only when createGlobalStyle is used.

Can you do something please ?

Thanks you in advance and best regards,
Louis Cuvelier.

**Comment by madlordory** [comment]
same problem! up ! up !

**Comment by undeadcat** [comment]
Issues with Prettier should be reported in the 'prettier' repository: https://github/prettier/prettier.  
You can see that it's an issue with Prettier by trying to format code [in the prettier playground](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEA3AhgJwATTtgXmwGcYBPAGzgBMA6agS1WwANhIKJMlMaBfFgB0owhlABWcMDADinAEboKLRqnYRO3AOa8EAgNzCwvdPDkRFFAMrkqKpus1IdcPS30gANCAgAHGAzQxMigWJgQAO4AClgIwSjoqBAM1F4g8pjoYADWcDBWvlliWsgwmACucN4AFjAAthQA6tUM8MSFYHBWca1MrWTI4MTB3mLEcJgwUZladejIAGZK497ixAAeAEKZOXlW6HVwADJicIvLVSBr61bFVACK5RDw5xQrIIWY45iDivKU0DSvkwYhgjRSMGqyAAHAAGbzAiDjRqZXyDYFwb6oM7eXgAR3KDF403Qs3mSCWb0u4zqDFKFWpdzgj2eZwpF28MHQ8nB1EhyAATJzMgwKMUAMIQOpzQZQPBpcrjAAq3PilPGfD4QA) or by using prettier from the command line.

Seems like previously methods like `injectGlobal` were supported, but then support was dropped in [this issue](https://github.com/prettier/prettier/pull/2337#issuecomment-311803127). Support for `createGlobalStyle` was later [declined](https://github.com/prettier/prettier/issues/5386).
