### ISSUE TITLE
No autocomplete for styled-components in Webstorm

### ISSUE THREAD

**Issue by adrianczuczka** [styled-components/webstorm-styled-components#70]
* **IDE name and version:** 
Webstorm 2019.1.3
* **Styled-components plugin version:** 
1.0.8

## Problem description:
Webstorm is currently not able to autocomplete styled-components when they are used. This is quite annoying, especially for projects with many components. This issue is identical to https://youtrack.jetbrains.com/issue/WEB-33709 .

**Comment by BeaRRRRR** [comment]
They fixed it in builds 193.1232, 192.5871 but this builds are only available in the eap, so you just need to go to File | Settings | Appearance and Behavior | System Settings | Updates , select Early Access Program in the dropdown, hit check now and, finally ,update

**Comment by prigara** [comment]
As @BeaRRRRR has mentioned, WebStorm 2019.2.1 Early Access that fixes the issue is available for the download here: https://confluence.jetbrains.com/display/WI/WebStorm+EAP The stable version will be available next week. Closing this issue now.
