### ISSUE TITLE
Plugin not working in Webstorm version 2019.1 

### ISSUE THREAD

**Issue by mqliutie** [styled-components/webstorm-styled-components#74]
![image](https://user-images.githubusercontent.com/11795518/65401518-30658480-ddfb-11e9-9bd9-d56d73a17151.png)
![image](https://user-images.githubusercontent.com/11795518/65401524-3e1b0a00-ddfb-11e9-9640-9bdd7a470fb2.png)

**Comment by undeadcat** [comment]
By default the plugin highlights inside strings where the tag  starts with `styled`, not `style`.

If you're importing styled-components with something like `import style from 'styled-components', you can 'style' to the list of tags to highlight using the configuration feature: https://github.com/styled-components/webstorm-styled-components#configuration.
