### ISSUE TITLE
Not working on 2019.3 ?

### ISSUE THREAD

**Issue by fatlinesofcode** [styled-components/webstorm-styled-components#80]
I just updated to PhpStorm 2019.3 and the highlight doesnt seem to work for me. Was working fine in 2019.2

![Screen Shot 2019-12-17 at 1 44 44 pm](https://user-images.githubusercontent.com/505776/70960807-2c809000-20d4-11ea-9beb-3cfc4a2dfb0c.png)

**Comment by undeadcat** [comment]
What plugin version are you using? 
There was an issue that prevented the plugin from working in 2019.3 but it was fixed in plugin v. 1.0.11: https://github.com/styled-components/webstorm-styled-components/issues/72

**Comment by fatlinesofcode** [comment]
im using plugin v1.1

**Comment by undeadcat** [comment]
@fatlinesofcode, It seems to work for me with the same versions and the same code sample.
Are there any exceptions in IDE logs (you can view them via Help Menu -> Show Log)?

Is the example above enough to reproduce the issue for you in a new project or is there maybe something else missing from the example?

**Comment by fatlinesofcode** [comment]
hi @undeadcat I cant see any exceptions in the log.

I seem to be getting css suggestions but no syntax highlighting 🤔 

<img width="473" alt="Screen Shot 2019-12-18 at 9 54 12 pm" src="https://user-images.githubusercontent.com/505776/71080527-6ee3c300-21e1-11ea-8998-1332b17011da.png">

I'm on mac and used latest styled-components v5-rc2 (if that makes any difference)

**Comment by undeadcat** [comment]
Based on the latest screenshot where  you're seeing completion and a red color picker icon on the gutter next to `background-color: red`, it seems likely that this plugin is correctly marking the string as styled-components.

This plugin only marks certain strings as styled-components, highlighting individual syntax elements inside them is the IDE's job and may depend on things like the particular IDE color scheme used.

Can you see if the issue exists with a different editor color scheme?

**Comment by fatlinesofcode** [comment]
thanks @undeadcat , yes looks like the issue related to the custom them i have. Plugin works fine with any of the default themes. Css and Scss files work fine with my custom theme. Any ideas on how I can fix my theme to also work with the plugin?

**Comment by undeadcat** [comment]
@fatlinesofcode, Unfortunately, I can't say for sure.
Try it out with different CSS-related settings and different colors for JS strings. Or try the WebStorm support forum: https://intellij-support.jetbrains.com/hc/en-us/community/topics/200367229-WebStorm

**Comment by fatlinesofcode** [comment]
adding the fix here for archives : 

_In language injections, foreground color is normally taken from the injected language highlighting settings, unless the color is specified explicitly in Preferences | Editor | Colors & Fonts | General / Code / Injected language fragment, Foreground.. In my scheme I had it set to #F8F8F2. Clearing the checkbox should fixed the issue_
