### ISSUE TITLE
Doesn't work with latest WebStorm

### ISSUE THREAD

**Issue by lebedev** [styled-components/webstorm-styled-components#85]
* **IDE name and version:** 
WebStorm 2019.3.4
Build #WS-193.6911.28, built on March 18, 2020
* **Styled-components plugin version:** 
1.1

## Problem description:

Doesn't highlight anymore since a couple of versions of WebStorm ago.

**Comment by FrankFang** [comment]
It works for me
![image](https://user-images.githubusercontent.com/839559/78137917-ac025700-7458-11ea-85f6-d1601257c59a.png)

**Comment by lebedev** [comment]
@FrankFang I think It stopped working for me roughly after I updated WebStorm from `2019.3` to `2019.3.1` or something. Current version is `2019.3.4`.

**Comment by co1in** [comment]
Can't install at all in 2020.1
```
WebStorm 2020.1
Build #WS-201.6668.106, built on April 6, 2020
Runtime version: 11.0.6+8-b765.25 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.15.3
```

**Comment by DanielOrtel** [comment]
FYI: installing on `2020.1` now works.

**Comment by lebedev** [comment]
@DanielOrtel thanks for the info. It seems to be working well on `2020.1` indeed, including highlighting. Closing the issue.
