### ISSUE TITLE
Re-configure branch protection policy for this repo

### ISSUE THREAD

**Issue by prigara** [styled-components/webstorm-styled-components#93]
Hi,

We, the WebStorm team, would like to ship the styled-components plugin by default with the IDE.
To make it easier for us to make changes and build the plugin, we want to make its sources available inside our internal monorepo.
At the same time, we really want to keep the project part of the styled component organisation and allow others easily contribute to it. 

Here's a workflow we would like to implement to solve this (and we are already using for [intellij-community](https://github.com/JetBrains/intellij-community) and [intellij-plugins](https://github.com/JetBrains/intellij-plugins) repos):
- We'll copy the source code to the JetBrains repo.
- A [special bot](https://github.com/intellij-monorepo-bot) will automatically sync all changes made in the JetBrains repo to this repo.
- All Pull Requests made to this repo will be automatically synced back to the JetBrains repo and merged from it. 

What changes in the repo's branch protection policies we need to implement this plan:
- Allow [intellij-monorepo-bot](https://github.com/intellij-monorepo-bot) to commit directly to the webstorm-styled-components' master, without review.

Unfortunately, no one working on the plugin on our team has access to the repo's settings to make this change.

@mxstbr, @probablyup what do you think? Could you please help us with that?

**Comment by mxstbr** [comment]
Done!

<img width="474" alt="Screenshot 2020-09-10 at 19 28 50" src="https://user-images.githubusercontent.com/7525670/92772347-eb37bb00-f39b-11ea-850a-ae0620d55ef7.png">
<img width="487" alt="Screenshot 2020-09-10 at 19 28 30" src="https://user-images.githubusercontent.com/7525670/92772351-ec68e800-f39b-11ea-827f-1f75f122fb7e.png">

**Comment by prigara** [comment]
Awesome! Thank you, Max!
